### ASK @Nsttt TO REQUEST CHANGES TO THIS FILE###
### ASK @Nsttt TO REQUEST CHANGES TO THIS FILE###
### ASK @Nsttt TO REQUEST CHANGES TO THIS FILE###
### ASK @Nsttt TO REQUEST CHANGES TO THIS FILE###
### ASK @Nsttt TO REQUEST CHANGES TO THIS FILE###

networks:
  sysarmy:
    driver: bridge

services:
  db:
    image: ghcr.io/gallegarmy/gallegarmy-telegram-bot/mysql:8.0.39
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
      args:
        BASE_DIRECTORY: .docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /docker-data/sysarmy:/var/lib/mysql
    networks:
      - sysarmy
    restart: unless-stopped

  telegram-bot:
    image: ghcr.io/gallegarmy/gallegarmy-telegram-bot:latest
    build:
      context: .
      dockerfile: .docker/telegram_bot/Dockerfile
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      BOT_TOKEN: ${BOT_TOKEN}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      EVENTBRITE_ORGANIZATION_ID: ${EVENTBRITE_ORGANIZATION_ID}
      EVENTBRITE_API: ${EVENTBRITE_API}
      EVENTBRITE_TOKEN: ${EVENTBRITE_TOKEN}
      TEST_MODE: ${TEST_MODE}
    depends_on:
      - db
    networks:
      - sysarmy
    restart: unless-stopped
