volumes:
  db_data:

networks:
  karma_net:
    driver: bridge

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - karma_net
    restart: unless-stopped

  telegram-bot:
    image: ghcr.io/gallegarmy/gallegarmy-telegram-bot:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      BOT_TOKEN: ${BOT_TOKEN}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - karma_net
    restart: unless-stopped
