[project]
dependencies = [
    "ruff>=0.6.2",
]
description = "Add your description here"
name = "gallegarmy-telegram-bot"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
